// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Captcha(arg1) {
  return window['go']['app']['App']['Captcha'](arg1);
}

export function ChooseDirectory() {
  return window['go']['app']['App']['ChooseDirectory']();
}

export function ChooseFile() {
  return window['go']['app']['App']['ChooseFile']();
}

export function ChooseFolder() {
  return window['go']['app']['App']['ChooseFolder']();
}

export function Download(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Download'](arg1, arg2, arg3, arg4);
}

export function Images() {
  return window['go']['app']['App']['Images']();
}

export function List(arg1) {
  return window['go']['app']['App']['List'](arg1);
}

export function Login(arg1) {
  return window['go']['app']['App']['Login'](arg1);
}

export function Process(arg1) {
  return window['go']['app']['App']['Process'](arg1);
}

export function View(arg1) {
  return window['go']['app']['App']['View'](arg1);
}
