// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {response} from '../models';
import {app} from '../models';

export function Captcha(arg1:string):Promise<response.Reply>;

export function ChooseDirectory():Promise<response.Reply>;

export function ChooseFile():Promise<response.Reply>;

export function ChooseFolder():Promise<response.Reply>;

export function Download(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<response.Reply>;

export function Images():Promise<response.Reply>;

export function List(arg1:string):Promise<response.Reply>;

export function Login(arg1:app.LoginRequest):Promise<response.Reply>;

export function Process(arg1:Array<app.ProcessRequest>):Promise<response.Reply>;

export function View(arg1:string):Promise<response.Reply>;
